# Setup
title:               Edward Yu
tagline:             'personal website'
description:         'personal website of Edward Yu'
url:                 http://quant.am
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Edward Yu
  url:               http://quant.am
  email:             edwardy20@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
